[#383] filter: Add payload and homomorphic hash filter methods
nspcc-dev/neofs-sdk-go pull request #386
Opened 2023-04-13 11:17 UTC by smallhive

close #383

2023-04-13 20:39 UTC, roman-khimov commented on object/search.go
> +// Example for `sum` creation:
https://go.dev/blog/examples and maybe this one is for checksum.SHA256 really.

2023-04-13 20:39 UTC, roman-khimov commented on object/search.go
> +// `sum` type must be github.com/nspcc-dev/neofs-sdk-go/checksum.SHA256
I think if you're to just reference `checksum.SHA256` (without full package name) it should work, https://go.dev/doc/comment.

2023-04-14 10:21 UTC, cthulhu-rider requested changes

2023-04-14 10:21 UTC, cthulhu-rider commented on object/search.go
> +func (f *SearchFilters) AddPayloadHashFilter(m SearchMatchType, sum checksum.Checksum) {
`checksum.Checksum` type is too generic here and may lead to unexpected behavior. Example: in unit test you pass SHA-256 checksum in both cases, but it isn't homomorphic.

In total, I propose to accept strict checksum 
```suggestion
func (f *SearchFilters) AddPayloadHashFilter(m SearchMatchType, sum [sha256.Size]byte) {
```
(`tz.Size` for homomorphic method)

2023-04-15 11:37 UTC, roman-khimov approved these changes

2023-04-17 09:23 UTC, cthulhu-rider approved these changes

2023-04-17 11:44 UTC, merged