Use CID to prevent incorrect usage in netmap
nspcc-dev/neofs-sdk-go pull request #396
Opened 2023-04-19 04:43 UTC by smallhive

close #216

2023-04-19 10:30 UTC, cthulhu-rider commented on netmap/netmap.go
> +	c.setPivot(containerID[:])
right now correct, but lets use dedicated `Encode` method

2023-04-19 11:11 UTC, cthulhu-rider commented
@smallhive btw how about https://pkg.go.dev/github.com/nspcc-dev/neofs-sdk-go/netmap#NetMap.PlacementVectors? if u wanna refactor it in a separate PR then current one shouldn't close an issue.

2023-04-19 11:11 UTC, cthulhu-rider approved these changes

2023-04-19 13:48 UTC, smallhive commented
Completed in this PR

2023-04-19 18:17 UTC, roman-khimov requested changes

2023-04-19 18:17 UTC, roman-khimov commented on netmap/netmap.go
> +func (m NetMap) PlacementVectors(vectors [][]NodeInfo, containerID cid.ID) ([][]NodeInfo, error) {
It should be `oid` here. And comment needs to be updated.

2023-04-20 11:52 UTC, roman-khimov approved these changes

2023-04-20 11:52 UTC, roman-khimov commented
There is some problem with tests though.

2023-04-20 11:54 UTC, smallhive commented
Yes, known issue. Me and @cthulhu-rider investigating it

2023-04-21 06:27 UTC, smallhive commented
Tests problems were solved

2023-04-21 10:06 UTC, roman-khimov approved these changes

2023-04-21 12:25 UTC, merged