Refactor and document `eacl` package
nspcc-dev/neofs-sdk-go pull request #526
Opened 2023-10-10 09:21 UTC by cthulhu-rider

2023-10-11 05:27 UTC, smallhive reviewed
In my opinion, there are too many panics in code. Part of them can be replaced with regular errors.

2023-10-11 05:27 UTC, smallhive commented on eacl/table.go
> +	return *t.cid, true
`t.cid` is a pointer here, we may use this fact to remove the second bool returning value. And check the result, it is nil or not. Pros and cons?

2023-10-11 05:27 UTC, smallhive commented on eacl/target.go
> +		panic("empty slice of targets")
Panic? may be just an error like [here](https://github.com/nspcc-dev/neofs-sdk-go/pull/526/commits/17bfe148958ccc7b03acda65f53fdd038fcdd42e#diff-7464879ee44471d9d8b4aeacd8bee60829915e7783dbd2dc7dc2eed532c01a25R109)? We already have `error` returning value

2023-10-11 05:27 UTC, smallhive commented on eacl/filter.go
> +func (f Filter) validate() string {
I would suggest to replace `string` with `error`

2023-10-11 05:27 UTC, smallhive commented on eacl/target.go
> +		return "neither roles nor keys are presented"
I suggest here and below in the function to replace the string with an error

2023-10-11 05:27 UTC, smallhive commented on eacl/target.go
> +			panic(fmt.Sprintf("invalid role #%d: forbidden value %v of enum %T", i, t.roles[i], t.roles[i]))
And here we may return the error instead of panic

2023-10-11 05:27 UTC, smallhive commented on eacl/target.go
> +		ms[len(ms)-1].SetKeys(t.keys)
Right now, we have all the checks to be sure this row works appropriately. But one may change some of these checks, and in one moment `ms` can't be zero length => we have runtime panic.
Could we add a simple check `ms > 0`?

2023-11-14 16:18 UTC, roman-khimov reviewed
1. A single patch changing whole `eacl` is bad. It shouldn't be this way, it should be a series of patches.
2. Many of the conceptual fixes are nice (validators/system/multi role)
3. But renamings are better be avoided at this stage. We're at RC, there has to be a reason to change something.
4. New* constructors are nice and look fine in related PRs (less code bloat).

2023-11-14 16:18 UTC, roman-khimov commented on eacl/test/benchmark_test.go
> -func baseBenchmarkTableBinaryComparison(b *testing.B, factor int) {
We no longer care?

2023-11-14 16:18 UTC, roman-khimov commented on eacl/example_test.go
> +	friendPubKey := test.RandomPublicKey()
NACK. It's an example. It must not import any test packages, it should be something people can copy/paste. Sure, `randomPublicKey()` will need to be replaced, but at least one can see what's in there, unlike when it's an imported package.

2023-11-15 18:22 UTC, carpawell reviewed
Linter died.

2023-11-15 18:22 UTC, carpawell commented on eacl/filter.go
> +func NewFilter(typ HeaderType, key string, matcher Matcher, value string) Filter {
why so generic name for a header-typed filter?

2023-11-15 18:22 UTC, carpawell commented on eacl/filter.go
> +		panic(msg)
panic? i think we are getting rid of them in sdk (and least in constructors)

2023-11-15 18:22 UTC, carpawell commented on eacl/record.go
> +func (r Record) TargetBinaryKeys() [][]byte {
is it ok to have bytes here but `neofscrypto.PublicKey` in the func a few lines below?

2023-11-15 18:22 UTC, carpawell commented on eacl/table.go
> +// according to the first hit: if a rule with a certain index is applicable,
do we want this behavior? i would say that looking for every applicable rule and choosing the most restrictive looks better

2023-11-15 18:22 UTC, carpawell commented on eacl/table.go
> +func New(records []Record) Table {
agree. not sure a table without a container could be used, so `LimitByContainer` is useless also to me

2023-11-15 18:22 UTC, carpawell commented on eacl/table.go
> -func (t *Table) SetCID(cid cid.ID) {
btw, i do not agree that `Container` is somehow better than `CID`. less explicit, more things to keep in mind, struct context is required for code reading, and so on

2023-11-15 18:22 UTC, carpawell commented on eacl/target.go
> +func NewTarget(roles []Role, publicKeys []neofscrypto.PublicKey) Target {
again, why some version of a generic struct is more default than others? why keys are more default `New` than roles?

2023-11-15 18:22 UTC, carpawell commented on eacl/validator.go
> -func (v *Validator) CalculateAction(unit *ValidationUnit) (Action, bool) {
we are so get used to moving code from one repo to another and many other types of useless work. am not a conservative but can we at least explain why we moving smth in and out again?

2024-01-31 13:41 UTC, roman-khimov requested changes
Feedback must be addressed.

2024-09-16 08:13 UTC, cthulhu-rider commented
overlapped by #605

2024-09-16 08:13 UTC, closed without merging